### ISSUE TITLE
 Sign Up

### ISSUE THREAD

**Issue by avishekc** [santanupatra/5-star#1]
1.Click on google+ and facebook button, it is not working.
2. Alert message "cannot be null" should be changed to "cannot be  blank". E.g. Name field cannot be 
blank.
3. Once sign up done, user should be notified that sign up has been done successfully. Check your email to activate the account.
4. Implement the trim functionality in each field except in password and confirm password.

**Comment by nitspalash** [comment]
1.Click on google+ and facebook button, it is not working.  Done later after client provide social credentials
2. Alert message "cannot be null" should be changed to "cannot be blank". E.g. Name field cannot be
blank.  Done
3. Once sign up done, user should be notified that sign up has been done successfully. Check your email to activate the account.   Done
4. Implement the trim functionality in each field except in password and confirm password.  Done
