### ISSUE TITLE
Event Details

### ISSUE THREAD

**Issue by avishekc** [santanupatra/5-star#4]
Reserve button is taking time to open the form .
Confirm Booking >Enter date is taking back date which should not be.
![starreservedsuccessful](https://user-images.githubusercontent.com/39148761/40357634-7e24dc40-5dda-11e8-8c83-54efa4cb6731.png)

Browser back button enabled and user book/visit the same confirm booking page multiple times which should not be.
![starpayment](https://user-images.githubusercontent.com/39148761/40357856-0dc07f80-5ddb-11e8-8448-66fd2447b032.png)

Click on "Back to Reservation Details" page not found is showing.

**Comment by nitspalash** [comment]
Click on "Back to Reservation Details" page not found is showing. Done
Browser back button enabled and user book/visit the same confirm booking page multiple times which should not be.   Done

Reserve button is taking time to open the form .  Done
Confirm Booking >Enter date is taking back date which should not be.
