### ISSUE TITLE
Event details

### ISSUE THREAD

**Issue by avishekc** [santanupatra/5-star#6]
Enter date and time should not be select from back date and future date.
Payment section:- Payment gateway is showing blank.
CheckOut Details Form:- CVV no.  should shown as in encrypted format.
In saved card section any of the check box should be selected based on form selection.
Implement the trim functionality.
Email id field required.

**Comment by nitspalash** [comment]
Enter date and time should not be select from back date and future date. Not required
Payment section:- Payment gateway is showing blank.  Now payment working
CheckOut Details Form:- CVV no. should shown as in encrypted format. Not required
In saved card section any of the check box should be selected based on form selection. Not required
Implement the trim functionality. Not required
Email id field required. Not required
